import { useEffect, useState } from "react";
import { approvePartRequest, getBossPartRequests, rejectPartRequest, type PartRequest } from "../../api/partRequests";
import PageHeader from "../../components/PageHeader";

const badge = (status: PartRequest["status"]) => status === "PENDING" ? "bg-amber-100 text-amber-800" : status === "APPROVED" ? "bg-emerald-100 text-emerald-800" : "bg-rose-100 text-rose-800";
export default function PartRequestsPage() {
  const [requests, setRequests] = useState<PartRequest[]>([]); const [error, setError] = useState<string | null>(null); const [workingId, setWorkingId] = useState<number | null>(null);
  useEffect(() => { getBossPartRequests().then(setRequests).catch((e: Error) => setError(e.message)); }, []);
  async function decide(id: number, decision: "approve" | "reject") { setWorkingId(id); setError(null); try { const updated = decision === "approve" ? await approvePartRequest(id) : await rejectPartRequest(id); setRequests((current) => current.map((request) => request.id === id ? updated : request)); } catch (e) { setError(e instanceof Error ? e.message : "Could not update request."); } finally { setWorkingId(null); } }
  return <div><PageHeader title="Part requests" subtitle="Approve an order and add its quantity to stock, or reject it." crumbs={[{ label: "Boss", to: "/boss/mechanics" }, { label: "Part requests" }]} />
    {error && <div className="mt-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <div className="mt-4 overflow-x-auto rounded-xl border"><table className="w-full text-sm"><thead className="bg-slate-50 text-slate-600"><tr><th className="px-4 py-3 text-left">Mechanic</th><th className="px-4 py-3 text-left">Part</th><th className="px-4 py-3 text-left">Qty</th><th className="px-4 py-3 text-left">Note</th><th className="px-4 py-3 text-left">Status</th><th className="px-4 py-3 text-left">Actions</th></tr></thead><tbody>{requests.map((request) => <tr key={request.id} className="border-t"><td className="px-4 py-3">{request.mechanicName}</td><td className="px-4 py-3">{request.partName}</td><td className="px-4 py-3">{request.quantity}</td><td className="px-4 py-3">{request.note || "—"}</td><td className="px-4 py-3"><span className={`inline-flex rounded-full px-2 py-1 text-xs font-medium ${badge(request.status)}`}>{request.status}</span></td><td className="px-4 py-3"><div className="flex gap-2"><button className="rounded-lg border px-3 py-1 disabled:opacity-50" disabled={request.status !== "PENDING" || workingId === request.id} onClick={() => decide(request.id, "approve")}>Approve</button><button className="rounded-lg border px-3 py-1 disabled:opacity-50" disabled={request.status !== "PENDING" || workingId === request.id} onClick={() => decide(request.id, "reject")}>Reject</button></div></td></tr>)}</tbody></table>{requests.length === 0 && <p className="p-4 text-sm text-slate-500">No part requests yet.</p>}</div></div>;
}
