import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { getNotifications, markAllNotificationsRead, markNotificationRead, type Notification } from "../api/notifications";

export default function NotificationsPage() {
  const [items, setItems] = useState<Notification[]>([]); const [error, setError] = useState(""); const navigate = useNavigate();
  useEffect(() => { getNotifications().then(setItems).catch((e) => setError(e instanceof Error ? e.message : "Could not load notifications")); }, []);
  async function open(item: Notification) { try { if (!item.readAt) await markNotificationRead(item.id); window.dispatchEvent(new Event("notifications-updated")); if (item.link) navigate(item.link); else setItems((rows) => rows.map((row) => row.id === item.id ? {...row, readAt:new Date().toISOString()} : row)); } catch (e) { setError(e instanceof Error ? e.message : "Could not open notification"); } }
  async function readAll() { try { await markAllNotificationsRead(); setItems((rows) => rows.map((row) => ({...row, readAt:row.readAt ?? new Date().toISOString()}))); window.dispatchEvent(new Event("notifications-updated")); } catch (e) { setError(e instanceof Error ? e.message : "Could not update notifications"); } }
  return <><div className="flex items-start justify-between gap-3"><div><h2 className="text-xl font-bold">Notifications</h2><p className="text-sm text-slate-600">Updates about problems, estimates, and repairs.</p></div><button onClick={readAll} disabled={!items.some((item) => !item.readAt)} className="rounded-lg border px-3 py-2 text-sm disabled:opacity-40">Mark all read</button></div>{error && <p className="mt-4 rounded-lg bg-red-50 p-3 text-red-700">{error}</p>}<div className="mt-4 space-y-2">{items.map((item) => <button key={item.id} onClick={() => open(item)} className={`block w-full rounded-xl border p-4 text-left transition hover:bg-slate-50 ${item.readAt ? "bg-white" : "border-blue-200 bg-blue-50"}`}><div className="flex justify-between gap-3"><strong>{item.title}</strong>{!item.readAt && <span className="text-xs font-semibold text-blue-700">NEW</span>}</div><p className="mt-1 text-sm text-slate-700">{item.message}</p><p className="mt-2 text-xs text-slate-500">{new Date(item.createdAt).toLocaleString()}</p></button>)}{items.length === 0 && <p className="rounded-xl border p-4 text-sm text-slate-500">No notifications yet.</p>}</div></>;
}
